// Generated by FlutterFire CLI from Firebase project: dressernotifications
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP83_IrEGyx_b2F1Q1K9wHxSobBgBVgBU',
    appId: '1:189181709545:android:b77f250849f50677f9f478',
    messagingSenderId: '189181709545',
    projectId: 'dressernotifications',
    storageBucket: 'dressernotifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxEJHxMoHz9-49DB-_V_8UPTl7Nq_d7U',
    appId: '1:189181709545:ios:fa44507695877bdcf9f478',
    messagingSenderId: '189181709545',
    projectId: 'dressernotifications',
    storageBucket: 'dressernotifications.firebasestorage.app',
    iosBundleId: 'com.dresser.dresserApp',
  );
}
